// Automatically generated
 #include "gazebo/math/Angle.hh"
 #include "gazebo/math/Box.hh"
 #include "gazebo/math/Helpers.hh"
 #include "gazebo/math/MathTypes.hh"
 #include "gazebo/math/Matrix3.hh"
 #include "gazebo/math/Matrix4.hh"
 #include "gazebo/math/Plane.hh"
 #include "gazebo/math/Pose.hh"
 #include "gazebo/math/Quaternion.hh"
 #include "gazebo/math/Rand.hh"
 #include "gazebo/math/RotationSpline.hh"
 #include "gazebo/math/Spline.hh"
 #include "gazebo/math/Vector2d.hh"
 #include "gazebo/math/Vector2i.hh"
 #include "gazebo/math/Vector3.hh"
 #include "gazebo/math/Vector4.hh"

