/* config.h. Generated by CMake for SDFormat. */

/* Version number */
#define SDF_MAJOR_VERSION 1
#define SDF_MINOR_VERSION 4
#define SDF_PATCH_VERSION 11

#define SDF_VERSION "1.4"
#define SDF_VERSION_FULL "1.4.11"
#define SDF_VERSION_NAME 

#define SDF_VERSION_HEADER "Simulation Description Format (SDF), version 1.4\nCopyright (C) 2013 Open Source Robotics Foundation.\nReleased under the Apache 2 License.\nhttp://gazebosim.org/sdf\n\n"

/* #undef BUILD_TYPE_PROFILE */
/* #undef BUILD_TYPE_DEBUG */
/* #undef BUILD_TYPE_RELEASE */
/* #undef HAVE_URDFDOM */
#define USE_EXTERNAL_URDF 1

#define SDF_SHARE_PATH "/usr/share/"
#define SDF_VERSION_PATH "/usr/share/sdformat/1.4"
