#define TEST_INTEGRATION_PATH "/tmp/buildd/gazebo2-2.2.3/test/integration"
#define TEST_REGRESSION_PATH "/tmp/buildd/gazebo2-2.2.3/test/regression"
#define TEST_UNIT_PATH "/tmp/buildd/gazebo2-2.2.3/test/unit"
#define TEST_PATH "/tmp/buildd/gazebo2-2.2.3/test"
#define PROJECT_SOURCE_PATH "/tmp/buildd/gazebo2-2.2.3"
#define PROJECT_BINARY_PATH "/tmp/buildd/gazebo2-2.2.3/obj-x86_64-linux-gnu"
