/* config.h. Generated by CMake for Gazebo. */

/* Version number */
#define GAZEBO_MAJOR_VERSION 2
#define GAZEBO_MINOR_VERSION 2
#define GAZEBO_PATCH_VERSION 3

#define GAZEBO_VERSION "2.2"
#define GAZEBO_VERSION_FULL "2.2.3"
#define GAZEBO_VERSION_NAME lithium

#define GAZEBO_VERSION_HEADER "Gazebo multi-robot simulator, version 2.2.3\nCopyright (C) 2012-2014 Open Source Robotics Foundation.\nReleased under the Apache 2 License.\nhttp://gazebosim.org\n\n"

/* #undef BUILD_TYPE_PROFILE */
/* #undef BUILD_TYPE_DEBUG */
/* #undef BUILD_TYPE_RELEASE */
#define HAVE_CEGUI 1
/* #undef HAVE_OPENAL */
#define HAVE_FFMPEG 1
#define HAVE_LTDL 1
#define HAVE_DL 1
/* #undef ENABLE_SHADOWS */
/* #undef HAVE_BULLET */
/* #undef HAVE_SIMBODY */
/* #undef HAVE_DART */
#define INCLUDE_RTSHADER 1
/* #undef HAVE_GTS */
/* #undef HAVE_QWT */
/* #undef ENABLE_DIAGNOSTICS */

#ifdef BUILD_TYPE_PROFILE
#include <google/heap-checker.h>
#endif
